version: 0.2
phases:
  pre_build:
    commands:
      - echo "Iniciando fase de pre-construcción..."
      - echo "Autenticando con AWS ECR..."
      - "aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
      - echo "sesion iniciada en aws"
      - "IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - echo "imagen tageada"
      - IMAGE_REPO_NAME=732963826765.dkr.ecr.us-east-2.amazonaws.com/api/ecomerce
      - echo "imagen asignada desde el repo"
      - IMAGE_FULL_NAME=$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo "Nombre de la imagen Docker: $IMAGE_FULL_NAME"
  build:
    commands:
      - echo "Iniciando fase de construcción..."
      - ./mvnw clean package -DskipTests
      - echo "Construyendo la imagen Docker..."
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME $IMAGE_FULL_NAME
  post_build:
    commands:
      - echo "Iniciando fase de post-construcción..."
      - echo "Subiendo la imagen Docker a ECR..."
      - docker push $IMAGE_FULL_NAME
      - echo "Imagen Docker subida a $IMAGE_FULL_NAME"
      # Si también necesitas actualizar la definición de tarea de ECS, descomenta y ajusta esto
      # - echo "Actualizando la definición de tarea de ECS..."
      # - TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition tu-familia-de-tarea --region $AWS_DEFAULT_REGION --output json)
      # - UPDATED_TASK_DEFINITION=$(echo "$TASK_DEFINITION" | jq ".taskDefinition | .containerDefinitions[0].image = \"$IMAGE_FULL_NAME\"")
      # - aws ecs register-task-definition --family tu-familia-de-tarea --container-definitions "$(echo "$UPDATED_TASK_DEFINITION" | jq '.containerDefinitions')" --volumes "$(echo "$TASK_DEFINITION" | jq '.volumes')" --placement-constraints "$(echo "$TASK_DEFINITION" | jq '.placementConstraints')" --network-mode "$(echo "$TASK_DEFINITION" | jq '.networkMode')" --cpu "$(echo "$TASK_DEFINITION" | jq '.cpu')" --memory "$(echo "$TASK_DEFINITION" | jq '.memory')" --region $AWS_DEFAULT_REGION --output json
      # - echo "Definición de tarea actualizada."
artifacts:
  files:
    - '**/*' # O los archivos específicos que quieras como artefactos
